-- Projects Table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  key TEXT NOT NULL,
  color TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Task Statuses (Master Data per Project)
CREATE TABLE IF NOT EXISTS task_statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Task Priorities (Master Data per Project)
CREATE TABLE IF NOT EXISTS task_priorities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Task Types (Master Data per Project)
CREATE TABLE IF NOT EXISTS task_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  icon TEXT,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tasks Table (Recursive for Subtasks)
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  parent_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  status_id BIGINT REFERENCES task_statuses(id),
  priority_id BIGINT REFERENCES task_priorities(id),
  type_id BIGINT REFERENCES task_types(id),
  completed BOOLEAN DEFAULT false,
  due_date DATE,
  assignee_id UUID REFERENCES auth.users(id),
  section_id TEXT, -- Keep for Kanban column if status_id is not enough or for UI state
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Activities Table
CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'history' or 'comment'
  user_name TEXT, -- Fallback if not using auth user profiles relation yet
  text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Wikis Table
CREATE TABLE IF NOT EXISTS wikis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT,
  updated_by TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) - Optional for now but recommended
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_priorities ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE wikis ENABLE ROW LEVEL SECURITY;

-- Create Policy to allow anonymous read/write (FOR DEVELOPMENT ONLY)
-- In production, you should restrict this to authenticated users
-- Checking existence complicates policies in simple SQL, usually dropping first or checking pg_policies is needed. 
-- For simplicity in this specific migration fix, we'll try to drop if exists or just leave them (creation might fail if exists).
-- A safer way for idempotent policy creation:
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for projects') THEN
        CREATE POLICY "Allow public access for projects" ON projects FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for task_statuses') THEN
        CREATE POLICY "Allow public access for task_statuses" ON task_statuses FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for task_priorities') THEN
        CREATE POLICY "Allow public access for task_priorities" ON task_priorities FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for task_types') THEN
        CREATE POLICY "Allow public access for task_types" ON task_types FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for tasks') THEN
        CREATE POLICY "Allow public access for tasks" ON tasks FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for activities') THEN
        CREATE POLICY "Allow public access for activities" ON activities FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for wikis') THEN
        CREATE POLICY "Allow public access for wikis" ON wikis FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Force trigger migration workflow for verification (Retry after config fix)

