-- Sections Table
CREATE TABLE IF NOT EXISTS sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add section_id to tasks if not exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'section_id') THEN
        ALTER TABLE tasks ADD COLUMN section_id BIGINT REFERENCES sections(id) ON DELETE SET NULL;
    END IF;
END $$;

-- RLS
ALTER TABLE sections ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for sections') THEN
        CREATE POLICY "Allow public access for sections" ON sections FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
