-- Task-Project Many-to-Many Relationship
CREATE TABLE IF NOT EXISTS task_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(task_id, project_id)
);

-- Enable RLS
ALTER TABLE task_projects ENABLE ROW LEVEL SECURITY;

-- Create Policy
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for task_projects') THEN
        CREATE POLICY "Allow public access for task_projects" ON task_projects FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Migrate existing data
INSERT INTO task_projects (task_id, project_id, position)
SELECT id, project_id, 0
FROM tasks
WHERE project_id IS NOT NULL
ON CONFLICT (task_id, project_id) DO NOTHING;

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_task_projects_task_id ON task_projects(task_id);
CREATE INDEX IF NOT EXISTS idx_task_projects_project_id ON task_projects(project_id);
