-- Add project_members table for managing project members
-- This table stores the members of each project

CREATE TABLE IF NOT EXISTS project_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  email TEXT,
  avatar_color TEXT DEFAULT 'indigo',
  position INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(project_id, name)
);

-- Enable Row Level Security
ALTER TABLE project_members ENABLE ROW LEVEL SECURITY;

-- Create Policy to allow public access (FOR DEVELOPMENT ONLY)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_policies WHERE policyname = 'Allow public access for project_members') THEN
        CREATE POLICY "Allow public access for project_members" ON project_members FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Insert default members for all existing projects
INSERT INTO project_members (project_id, name, email, avatar_color, position)
SELECT 
    p.id as project_id,
    member_data.name,
    member_data.email,
    member_data.avatar_color,
    member_data.position
FROM projects p
CROSS JOIN (
    VALUES 
        ('山田 太郎 (Yamada)', 'yamada@example.com', 'indigo', 1),
        ('鈴木 花子 (Suzuki)', 'suzuki@example.com', 'pink', 2),
        ('佐藤 健 (Sato)', 'sato@example.com', 'blue', 3),
        ('田中 美咲 (Tanaka)', 'tanaka@example.com', 'purple', 4)
) AS member_data(name, email, avatar_color, position)
WHERE NOT EXISTS (
    SELECT 1 FROM project_members pm 
    WHERE pm.project_id = p.id AND pm.name = member_data.name
);
